language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: jorgegalingp-github
    token:
      secure: 08b2105f72b819688d2907a95c4ed947b13edfad
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
